name: bnn-env
channels:
  - defaults
dependencies:
  - python=3.11
  - asttokens=2.0.5
  - backcall=0.2.0
  - bottleneck=1.3.5
  - certifi=2023.7.22
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - conda-content-trust=0.1.1
  - conda-package-handling=1.8.1
  - decorator=5.1.1
  - executing=0.8.3
  - idna=3.3
  - jedi=0.18.1
  - matplotlib-inline=0.1.6
  - numexpr=2.8.4 
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - pytz=2022.7
  - ruamel_yaml=0.15.100
  - six=1.16.0
  - stack_data=0.2.0
  - toolz=0.12.0
  - tqdm=4.63.0
  - traitlets=5.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - xarray=2023.6.0
  - pip
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.6
    - aiohttp==3.11.12
    - aiosignal==1.3.2
    - alabaster==0.7.16
    - arrow==1.3.0
    - arviz==0.17.1
    - astroid==3.3.8
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - asyncssh==2.20.0
    - atomicwrites==1.4.1
    - attrs==25.1.0
    - autopep8==2.0.4
    - babel==2.17.0
    - backports.tarfile==1.2.0
    - beautifulsoup4==4.13.3
    - binaryornot==0.4.4
    - black==25.1.0
    - bleach==6.2.0
    - bokeh==3.4.3
    - brotlipy==0.7.0
    - chardet==5.2.0
    - click==8.1.8
    - cloudpickle==3.1.1
    - comm==0.2.2
    - conda==4.14.0
    - contourpy==1.2.0
    - cookiecutter==2.6.0
    - corner==2.2.3
    - cryptography==44.0.1
    - cycler==0.12.1
    - debugpy==1.8.12
    - defusedxml==0.7.1
    - Deprecated==1.2.18
    - diff-match-patch==20241021
    - dill==0.3.9
    - docstring-to-markdown==0.15
    - docutils==0.21.2
    - emcee==3.1.6
    - exceptiongroup==1.2.2
    - fastjsonschema==2.21.1
    - filelock==3.17.0
    - flake8==7.1.2
    - flatbuffers==25.2.10
    - fonttools==4.44.0
    - freenect==0.0.0
    - frozenlist==1.5.0
    - fsspec==2025.2.0
    - gast==0.6.0
    - google-pasta==0.2.0
    - googlemaps==4.10.0
    - grpcio==1.70.0
    - h5netcdf==1.5.0
    - h5py==3.13.0
    - imagesize==1.4.1
    - importlib-resources==6.1.1
    - importlib_metadata==8.6.1
    - inflection==0.5.1
    - iniconfig==1.1.1
    - intervaltree==3.1.0
    - ipykernel==6.29.5
    - ipython==8.18.1
    - isort==6.0.0
    - jaraco.classes==3.4.0
    - jaraco.context==6.0.1
    - jaraco.functools==4.1.0
    - jeepney==0.8.0
    - jellyfish==1.1.3
    - Jinja2==3.1.5
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter_client==8.6.3
    - jupyter_core==5.7.2
    - jupyterlab_pygments==0.3.0
    - keras==3.8.0
    - keyring==25.6.0
    - kiwisolver==1.4.5
    - libclang==18.1.1
    - Markdown==3.7
    - markdown-it-py==3.0.0
    - MarkupSafe==3.0.2
    - matplotlib==3.8.1
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mistune==3.1.2
    - ml-dtypes==0.3.2
    - more-itertools==10.6.0
    - mpmath==1.3.0
    - multidict==6.1.0
    - mypy-extensions==1.0.0
    - namex==0.0.8
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - numpy==1.24.0
    - numpydoc==1.8.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.1.105
    - odfpy==1.4.1
    - opt_einsum==3.4.0
    - optree==0.14.0
    - packaging==24.2
    - pandas==1.5.3
    - pandocfilters==1.5.1
    - pathspec==0.12.1
    - Pillow==10.1.0
    - platformdirs==4.3.6
    - pluggy==1.0.0
    - prompt_toolkit==3.0.50
    - propcache==0.2.1
    - protobuf==4.25.6
    - psutil==7.0.0
    - py==1.11.0
    - pycodestyle==2.12.1
    - pycosat==0.6.3
    - pydocstyle==6.3.0
    - pyflakes==3.2.0
    - PyGithub==2.6.0
    - Pygments==2.19.1
    - PyJWT==2.10.1
    - pylint==3.3.4
    - pylint-venv==3.0.4
    - pyls-spyder==0.4.0
    - PyNaCl==1.5.0
    - pyparsing==3.0.9
    - pypng==0.20220715.0
    - PyQt5==5.15.11
    - PyQt5-Qt5==5.15.16
    - PyQt5_sip==12.17.0
    - PyQtWebEngine==5.15.7
    - PyQtWebEngine-Qt5==5.15.16
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - pyTelegramBotAPI==4.7.0
    - pytest==7.1.3
    - python-lsp-black==2.0.0
    - python-lsp-jsonrpc==1.1.2
    - python-lsp-server==1.12.2
    - python-slugify==8.0.4
    - pytoolconfig==1.3.1
    - pytwalk @ pytwalk-1.9.0-py3-none-any.whl
    - pyuca==1.2
    - pyxdg==0.28
    - PyYAML==6.0.2
    - pyzmq==26.2.1
    - QDarkStyle==3.2.3
    - qrcode==7.4.2
    - qstylizer==0.2.4
    - QtAwesome==1.3.1
    - qtconsole==5.6.1
    - QtPy==2.4.3
    - referencing==0.36.2
    - requests==2.32.3
    - responses==0.25.3
    - rich==13.9.4
    - rope==1.13.0
    - rpds-py==0.22.3
    - Rtree==1.3.0
    - scipy==1.9.2
    - SecretStorage==3.3.3
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - Sphinx==7.4.7
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - spyder==6.0.4
    - spyder-kernels==3.0.3
    - superqt==0.7.1
    - sympy==1.13.3
    - tabulate==0.9.0
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.16.2
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.5.0
    - text-unidecode==1.3
    - textdistance==4.6.3
    - three-merge==0.1.1
    - tinycss2==1.4.0
    - tomli==2.0.1
    - tomlkit==0.13.2
    - torch==2.1.0
    - tornado==6.4.2
    - triton==2.1.0
    - types-python-dateutil==2.9.0.20241206
    - utm=0.7.0
    - ujson==5.10.0
    - watchdog==6.0.0
    - webencodings==0.5.1
    - Werkzeug==3.1.3
    - whatthepatch==1.0.7
    - wrapt==1.17.2
    - wurlitzer==3.1.1
    - xarray-einstats==0.7.0
    - xyzservices==2025.1.0
    - yapf==0.43.0
    - yarl==1.18.3
    - zipp==3.21.0
