name: bnn-env
channels:
  - defaults
dependencies:
  - python=3.11
  - toolz
  - tqdm
  - pip
  - pip:
    - arviz
    - bokeh
    - conda
    - corner
    - emcee
    - ipython
    - matplotlib
    - numpy==1.24.0
    - pandas
    - pyro-api
    - pyro-ppl
    - http://www.cimat.mx/~jac/twalk/pytwalk-1.9.0-py3-none-any.whl
    - scipy
    - spyder
    - torch
